import type { Issue } from '../../shared-types.js';
import { createRegexRule, type Rule } from '../types.js';

export const punctuationRules: Rule[] = [
  // ═══ Missing Question Mark (PU_QMK) ═══
  createRegexRule({
    id: 'PU_QMK_how_are_you',
    category: 'grammar',
    pattern: /\bhow\s+are\s+you\s+doing\s*$/i,
    suggestion: 'How are you doing?',
    reason: 'Questions should end with a question mark.',
  }),
  createRegexRule({
    id: 'PU_QMK_how_do_you',
    category: 'grammar',
    pattern: /\bhow\s+do\s+you\b[^?]*$/i,
    suggestion: (m) => m[0].trim() + '?',
    reason: 'This appears to be a question. Add a question mark at the end.',
  }),
  createRegexRule({
    id: 'PU_QMK_direct_question',
    category: 'grammar',
    pattern: /^(What|Where|When|Why|Who|Whom|Which|Whose|How)\s+\w[^?!.]*[a-zA-Z0-9]\s*$/,
    suggestion: (m) => m[0].trim() + '?',
    reason: 'Questions starting with a question word should end with a question mark.',
  }),
  createRegexRule({
    id: 'PU_QMK_are_you',
    category: 'grammar',
    pattern: /^(Are|Is|Was|Were|Do|Does|Did|Have|Has|Had|Can|Could|Will|Would|Should|Shall|May|Might|Must)\s+\w[^?!.]*[a-zA-Z0-9]\s*$/,
    suggestion: (m) => m[0].trim() + '?',
    reason: 'Yes/no questions should end with a question mark.',
  }),

  // ═══ Hyphenation (PU_HYP) ═══
  createRegexRule({
    id: 'PU_HYP_well_known',
    category: 'grammar',
    pattern: /\ba\s+well\s+known\s+/i,
    suggestion: 'a well-known ',
    reason: 'Hyphenate compound adjectives before a noun: "well-known".',
  }),
  createRegexRule({
    id: 'PU_HYP_high_quality',
    category: 'grammar',
    pattern: /\ba\s+high\s+quality\s+/i,
    suggestion: 'a high-quality ',
    reason: 'Hyphenate compound adjectives before a noun: "high-quality".',
  }),
  createRegexRule({
    id: 'PU_HYP_long_term',
    category: 'grammar',
    pattern: /\ba\s+long\s+term\s+/i,
    suggestion: 'a long-term ',
    reason: 'Hyphenate compound adjectives before a noun: "long-term".',
  }),
  createRegexRule({
    id: 'PU_HYP_short_term',
    category: 'grammar',
    pattern: /\ba\s+short\s+term\s+/i,
    suggestion: 'a short-term ',
    reason: 'Hyphenate compound adjectives before a noun: "short-term".',
  }),
  createRegexRule({
    id: 'PU_HYP_full_time',
    category: 'grammar',
    pattern: /\ba\s+full\s+time\s+/i,
    suggestion: 'a full-time ',
    reason: 'Hyphenate compound adjectives before a noun: "full-time".',
  }),
  createRegexRule({
    id: 'PU_HYP_part_time',
    category: 'grammar',
    pattern: /\ba\s+part\s+time\s+/i,
    suggestion: 'a part-time ',
    reason: 'Hyphenate compound adjectives before a noun: "part-time".',
  }),
  createRegexRule({
    id: 'PU_HYP_real_time',
    category: 'grammar',
    pattern: /\b(a|the)\s+real\s+time\s+/i,
    suggestion: (m) => `${m[1]} real-time `,
    reason: 'Hyphenate compound adjectives before a noun: "real-time".',
  }),
  createRegexRule({
    id: 'PU_HYP_up_to_date',
    category: 'grammar',
    pattern: /\b(an?|the)\s+up\s+to\s+date\s+/i,
    suggestion: (m) => `${m[1]} up-to-date `,
    reason: 'Hyphenate compound adjectives before a noun: "up-to-date".',
  }),
  createRegexRule({
    id: 'PU_HYP_state_of_art',
    category: 'grammar',
    pattern: /\b(a|the)\s+state\s+of\s+the\s+art\s+/i,
    suggestion: (m) => `${m[1]} state-of-the-art `,
    reason: 'Hyphenate compound adjectives before a noun: "state-of-the-art".',
  }),
  createRegexRule({
    id: 'PU_HYP_day_to_day',
    category: 'grammar',
    pattern: /\b(a|the|our|my|your|his|her|their|its)\s+day\s+to\s+day\s+/i,
    suggestion: (m) => `${m[1]} day-to-day `,
    reason: 'Hyphenate compound adjectives before a noun: "day-to-day".',
  }),
  createRegexRule({
    id: 'PU_HYP_face_to_face',
    category: 'grammar',
    pattern: /\b(a|the)\s+face\s+to\s+face\s+/i,
    suggestion: (m) => `${m[1]} face-to-face `,
    reason: 'Hyphenate compound adjectives before a noun: "face-to-face".',
  }),
  createRegexRule({
    id: 'PU_HYP_one_on_one',
    category: 'grammar',
    pattern: /\b(a|the)\s+one\s+on\s+one\s+/i,
    suggestion: (m) => `${m[1]} one-on-one `,
    reason: 'Hyphenate compound adjectives before a noun: "one-on-one".',
  }),

  // ═══ Missing Apostrophe in Contractions (PU_APO) ═══
  createRegexRule({
    id: 'PU_APO_dont',
    category: 'grammar',
    pattern: /\bdont\b/i,
    suggestion: "don't",
    reason: 'Missing apostrophe in contraction "don\'t".',
  }),
  createRegexRule({
    id: 'PU_APO_cant',
    category: 'grammar',
    pattern: /\bcant\b/i,
    suggestion: "can't",
    reason: 'Missing apostrophe in contraction "can\'t".',
  }),
  createRegexRule({
    id: 'PU_APO_wont',
    category: 'grammar',
    pattern: /\bwont\b/i,
    suggestion: "won't",
    reason: 'Missing apostrophe in contraction "won\'t".',
  }),
  createRegexRule({
    id: 'PU_APO_havent',
    category: 'grammar',
    pattern: /\bhavent\b/i,
    suggestion: "haven't",
    reason: 'Missing apostrophe in contraction "haven\'t".',
  }),
  createRegexRule({
    id: 'PU_APO_hasnt',
    category: 'grammar',
    pattern: /\bhasnt\b/i,
    suggestion: "hasn't",
    reason: 'Missing apostrophe in contraction "hasn\'t".',
  }),
  createRegexRule({
    id: 'PU_APO_hadnt',
    category: 'grammar',
    pattern: /\bhadnt\b/i,
    suggestion: "hadn't",
    reason: 'Missing apostrophe in contraction "hadn\'t".',
  }),
  createRegexRule({
    id: 'PU_APO_im',
    category: 'grammar',
    pattern: /\bim\b/i,
    suggestion: "I'm",
    reason: 'Missing apostrophe in contraction "I\'m".',
  }),
  createRegexRule({
    id: 'PU_APO_ive',
    category: 'grammar',
    pattern: /\bive\b/i,
    suggestion: "I've",
    reason: 'Missing apostrophe in contraction "I\'ve".',
  }),
  createRegexRule({
    id: 'PU_APO_ill',
    category: 'grammar',
    pattern: /\bill\b/i,
    suggestion: "I'll",
    reason: 'Missing apostrophe in contraction "I\'ll".',
  }),
  createRegexRule({
    id: 'PU_APO_youre',
    category: 'grammar',
    pattern: /\byoure\b/i,
    suggestion: "you're",
    reason: 'Missing apostrophe in contraction "you\'re".',
  }),
  createRegexRule({
    id: 'PU_APO_youve',
    category: 'grammar',
    pattern: /\byouve\b/i,
    suggestion: "you've",
    reason: 'Missing apostrophe in contraction "you\'ve".',
  }),
  createRegexRule({
    id: 'PU_APO_youll',
    category: 'grammar',
    pattern: /\byoull\b/i,
    suggestion: "you'll",
    reason: 'Missing apostrophe in contraction "you\'ll".',
  }),
  createRegexRule({
    id: 'PU_APO_theyve',
    category: 'grammar',
    pattern: /\btheyve\b/i,
    suggestion: "they've",
    reason: 'Missing apostrophe in contraction "they\'ve".',
  }),
  createRegexRule({
    id: 'PU_APO_theyll',
    category: 'grammar',
    pattern: /\btheyll\b/i,
    suggestion: "they'll",
    reason: 'Missing apostrophe in contraction "they\'ll".',
  }),
  createRegexRule({
    id: 'PU_APO_theyre',
    category: 'grammar',
    pattern: /\btheyre\b/i,
    suggestion: "they're",
    reason: 'Missing apostrophe in contraction "they\'re".',
  }),
  createRegexRule({
    id: 'PU_APO_weve',
    category: 'grammar',
    pattern: /\bweve\b/i,
    suggestion: "we've",
    reason: 'Missing apostrophe in contraction "we\'ve".',
  }),
  createRegexRule({
    id: 'PU_APO_well_contr',
    category: 'grammar',
    pattern: /\bwell\b(?=\s+(be|have|see|go|get|do|make|take|find|give|tell|come|know))/i,
    suggestion: "we'll",
    reason: 'Missing apostrophe in contraction "we\'ll".',
  }),
  createRegexRule({
    id: 'PU_APO_were_contr',
    category: 'grammar',
    pattern:
      /\bwere\b(?=\s+(going|coming|doing|making|getting|trying|looking|working|playing|running|having|being))/i,
    suggestion: "we're",
    reason: 'Missing apostrophe in contraction "we\'re".',
  }),
  createRegexRule({
    id: 'PU_APO_hes',
    category: 'grammar',
    pattern: /\bhes\b/i,
    suggestion: "he's",
    reason: 'Missing apostrophe in contraction "he\'s".',
  }),
  createRegexRule({
    id: 'PU_APO_shes',
    category: 'grammar',
    pattern: /\bshes\b/i,
    suggestion: "she's",
    reason: 'Missing apostrophe in contraction "she\'s".',
  }),
  createRegexRule({
    id: 'PU_APO_thats',
    category: 'grammar',
    pattern: /\bthats\b/i,
    suggestion: "that's",
    reason: 'Missing apostrophe in contraction "that\'s".',
  }),
  createRegexRule({
    id: 'PU_APO_whats',
    category: 'grammar',
    pattern: /\bwhats\b/i,
    suggestion: "what's",
    reason: 'Missing apostrophe in contraction "what\'s".',
  }),
  createRegexRule({
    id: 'PU_APO_whos',
    category: 'grammar',
    pattern: /\bwhos\b/i,
    suggestion: "who's",
    reason: 'Missing apostrophe in contraction "who\'s".',
  }),

  // ═══ Exclamation Mark Overuse ═══
  createRegexRule({
    id: 'PU_EXC_multiple',
    category: 'style',
    pattern: /!{2,}/g,
    suggestion: '!',
    reason: 'Multiple exclamation marks are excessive. Use a single one.',
  }),

  // ═══ Spelling Pattern Rules (SP from Part 1) ═══
  // Additional commonly misspelled words not in base spelling.ts
  ...(
    Object.entries({
      accomodate: 'accommodate',
      aquire: 'acquire',
      arguement: 'argument',
      bizzare: 'bizarre',
      Carribean: 'Caribbean',
      cemetary: 'cemetery',
      committie: 'committee',
      concious: 'conscious',
      consience: 'conscience',
      dilema: 'dilemma',
      equivilant: 'equivalent',
      exagerate: 'exaggerate',
      foriegn: 'foreign',
      guarentee: 'guarantee',
      hierarcy: 'hierarchy',
      humourous: 'humorous',
      indispensible: 'indispensable',
      liason: 'liaison',
      miscellaneous: 'miscellaneous',
      occurrance: 'occurrence',
      paralell: 'parallel',
      percieve: 'perceive',
      perserverance: 'perseverance',
      personell: 'personnel',
      posession: 'possession',
      priviledge: 'privilege',
      restarant: 'restaurant',
      rythm: 'rhythm',
      sargeant: 'sergeant',
      sincerly: 'sincerely',
      subttle: 'subtle',
      supercede: 'supersede',
      tendancy: 'tendency',
      threshhold: 'threshold',
      tommorrow: 'tomorrow',
      unneccesary: 'unnecessary',
      vaccuum: 'vacuum',
      Wendsday: 'Wednesday',
      wierd: 'weird',
    }) as [string, string][]
  ).map(([wrong, correct]) =>
    createRegexRule({
      id: `SP_EXT_${wrong.toLowerCase().replace(/[^a-z]/g, '')}`,
      category: 'spelling',
      pattern: new RegExp(`\\b${wrong}\\b`, 'i'),
      suggestion: correct,
      reason: `Misspelled word. The correct spelling is "${correct}".`,
    }),
  ),
];
