import type { Issue } from '../../shared-types.js';
import { createRegexRule, type Rule } from '../types.js';

export const verbTenseRules: Rule[] = [
  // ═══ Irregular Verb Errors — Extended (VT_IRR) ═══
  // Past tense regularization errors (extending grammar.ts)
  createRegexRule({
    id: 'VT_drived',
    category: 'grammar',
    pattern: /\bdrived\b/i,
    suggestion: 'drove',
    reason: '"Drived" is not a word. The past tense of "drive" is "drove".',
  }),
  createRegexRule({
    id: 'VT_speaked',
    category: 'grammar',
    pattern: /\bspeaked\b/i,
    suggestion: 'spoke',
    reason: '"Speaked" is not a word. The past tense of "speak" is "spoke".',
  }),
  createRegexRule({
    id: 'VT_writed',
    category: 'grammar',
    pattern: /\bwrited\b/i,
    suggestion: 'wrote',
    reason: '"Writed" is not a word. The past tense of "write" is "wrote".',
  }),
  createRegexRule({
    id: 'VT_beginned',
    category: 'grammar',
    pattern: /\bbeginned\b/i,
    suggestion: 'began',
    reason: '"Beginned" is not a word. The past tense of "begin" is "began".',
  }),
  createRegexRule({
    id: 'VT_choosed',
    category: 'grammar',
    pattern: /\bchoosed\b/i,
    suggestion: 'chose',
    reason: '"Choosed" is not a word. The past tense of "choose" is "chose".',
  }),
  createRegexRule({
    id: 'VT_drinked',
    category: 'grammar',
    pattern: /\bdrinked\b/i,
    suggestion: 'drank',
    reason: '"Drinked" is not a word. The past tense of "drink" is "drank".',
  }),
  createRegexRule({
    id: 'VT_flyed',
    category: 'grammar',
    pattern: /\bflyed\b/i,
    suggestion: 'flew',
    reason: '"Flyed" is not a word. The past tense of "fly" is "flew".',
  }),
  createRegexRule({
    id: 'VT_freezed',
    category: 'grammar',
    pattern: /\bfreezed\b/i,
    suggestion: 'froze',
    reason: '"Freezed" is not a word. The past tense of "freeze" is "froze".',
  }),
  createRegexRule({
    id: 'VT_growed',
    category: 'grammar',
    pattern: /\bgrowed\b/i,
    suggestion: 'grew',
    reason: '"Growed" is not a word. The past tense of "grow" is "grew".',
  }),
  createRegexRule({
    id: 'VT_hided',
    category: 'grammar',
    pattern: /\bhided\b/i,
    suggestion: 'hid',
    reason: '"Hided" is not a word. The past tense of "hide" is "hid".',
  }),
  createRegexRule({
    id: 'VT_leaved',
    category: 'grammar',
    pattern: /\bleaved\b/i,
    suggestion: 'left',
    reason: '"Leaved" is not a word. The past tense of "leave" is "left".',
  }),
  createRegexRule({
    id: 'VT_meaned',
    category: 'grammar',
    pattern: /\bmeaned\b/i,
    suggestion: 'meant',
    reason: '"Meaned" is not a word. The past tense of "mean" is "meant".',
  }),
  createRegexRule({
    id: 'VT_selled',
    category: 'grammar',
    pattern: /\bselled\b/i,
    suggestion: 'sold',
    reason: '"Selled" is not a word. The past tense of "sell" is "sold".',
  }),
  createRegexRule({
    id: 'VT_sitted',
    category: 'grammar',
    pattern: /\bsitted\b/i,
    suggestion: 'sat',
    reason: '"Sitted" is not a word. The past tense of "sit" is "sat".',
  }),
  createRegexRule({
    id: 'VT_sleeped',
    category: 'grammar',
    pattern: /\bsleeped\b/i,
    suggestion: 'slept',
    reason: '"Sleeped" is not a word. The past tense of "sleep" is "slept".',
  }),
  createRegexRule({
    id: 'VT_stealed',
    category: 'grammar',
    pattern: /\bstealed\b/i,
    suggestion: 'stole',
    reason: '"Stealed" is not a word. The past tense of "steal" is "stole".',
  }),
  createRegexRule({
    id: 'VT_swimmed',
    category: 'grammar',
    pattern: /\bswimmed\b/i,
    suggestion: 'swam',
    reason: '"Swimmed" is not a word. The past tense of "swim" is "swam".',
  }),
  createRegexRule({
    id: 'VT_teached',
    category: 'grammar',
    pattern: /\bteached\b/i,
    suggestion: 'taught',
    reason: '"Teached" is not a word. The past tense of "teach" is "taught".',
  }),
  createRegexRule({
    id: 'VT_throwed',
    category: 'grammar',
    pattern: /\bthrowed\b/i,
    suggestion: 'threw',
    reason: '"Throwed" is not a word. The past tense of "throw" is "threw".',
  }),
  createRegexRule({
    id: 'VT_weared',
    category: 'grammar',
    pattern: /\bweared\b/i,
    suggestion: 'wore',
    reason: '"Weared" is not a word. The past tense of "wear" is "wore".',
  }),
  createRegexRule({
    id: 'VT_winned',
    category: 'grammar',
    pattern: /\bwinned\b/i,
    suggestion: 'won',
    reason: '"Winned" is not a word. The past tense of "win" is "won".',
  }),
  createRegexRule({
    id: 'VT_catched',
    category: 'grammar',
    pattern: /\bcatched\b/i,
    suggestion: 'caught',
    reason: '"Catched" is not a word. The past tense of "catch" is "caught".',
  }),
  createRegexRule({
    id: 'VT_fighted',
    category: 'grammar',
    pattern: /\bfighted\b/i,
    suggestion: 'fought',
    reason: '"Fighted" is not a word. The past tense of "fight" is "fought".',
  }),
  createRegexRule({
    id: 'VT_feeled',
    category: 'grammar',
    pattern: /\bfeeled\b/i,
    suggestion: 'felt',
    reason: '"Feeled" is not a word. The past tense of "feel" is "felt".',
  }),
  createRegexRule({
    id: 'VT_finded',
    category: 'grammar',
    pattern: /\bfinded\b/i,
    suggestion: 'found',
    reason: '"Finded" is not a word. The past tense of "find" is "found".',
  }),
  createRegexRule({
    id: 'VT_forgetted',
    category: 'grammar',
    pattern: /\bforgetted\b/i,
    suggestion: 'forgot',
    reason: '"Forgetted" is not a word. The past tense of "forget" is "forgot".',
  }),
  createRegexRule({
    id: 'VT_gived',
    category: 'grammar',
    pattern: /\bgived\b/i,
    suggestion: 'gave',
    reason: '"Gived" is not a word. The past tense of "give" is "gave".',
  }),
  createRegexRule({
    id: 'VT_heared',
    category: 'grammar',
    pattern: /\bheared\b/i,
    suggestion: 'heard',
    reason: '"Heared" is not a word. The past tense of "hear" is "heard".',
  }),
  createRegexRule({
    id: 'VT_holded',
    category: 'grammar',
    pattern: /\bholded\b/i,
    suggestion: 'held',
    reason: '"Holded" is not a word. The past tense of "hold" is "held".',
  }),
  createRegexRule({
    id: 'VT_keeped',
    category: 'grammar',
    pattern: /\bkeeped\b/i,
    suggestion: 'kept',
    reason: '"Keeped" is not a word. The past tense of "keep" is "kept".',
  }),
  createRegexRule({
    id: 'VT_losted',
    category: 'grammar',
    pattern: /\blosted\b/i,
    suggestion: 'lost',
    reason: '"Losted" is not a word. The past tense of "lose" is "lost".',
  }),
  createRegexRule({
    id: 'VT_maked',
    category: 'grammar',
    pattern: /\bmaked\b/i,
    suggestion: 'made',
    reason: '"Maked" is not a word. The past tense of "make" is "made".',
  }),
  createRegexRule({
    id: 'VT_sayed',
    category: 'grammar',
    pattern: /\bsayed\b/i,
    suggestion: 'said',
    reason: '"Sayed" is not a word. The past tense of "say" is "said".',
  }),
  createRegexRule({
    id: 'VT_sended',
    category: 'grammar',
    pattern: /\bsended\b/i,
    suggestion: 'sent',
    reason: '"Sended" is not a word. The past tense of "send" is "sent".',
  }),
  createRegexRule({
    id: 'VT_spended',
    category: 'grammar',
    pattern: /\bspended\b/i,
    suggestion: 'spent',
    reason: '"Spended" is not a word. The past tense of "spend" is "spent".',
  }),
  createRegexRule({
    id: 'VT_standed',
    category: 'grammar',
    pattern: /\bstanded\b/i,
    suggestion: 'stood',
    reason: '"Standed" is not a word. The past tense of "stand" is "stood".',
  }),
  createRegexRule({
    id: 'VT_telled',
    category: 'grammar',
    pattern: /\btelled\b/i,
    suggestion: 'told',
    reason: '"Telled" is not a word. The past tense of "tell" is "told".',
  }),

  // ═══ Modal Perfect Errors (VT_MOD_001) ═══
  createRegexRule({
    id: 'VT_MOD_went',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+went\b/i,
    suggestion: (m) => `${m[1]} have gone`,
    reason: 'After "modal + have", use the past participle: "gone", not "went".',
  }),
  createRegexRule({
    id: 'VT_MOD_ran',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+ran\b/i,
    suggestion: (m) => `${m[1]} have run`,
    reason: 'After "modal + have", use the past participle: "run", not "ran".',
  }),
  createRegexRule({
    id: 'VT_MOD_ate',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+ate\b/i,
    suggestion: (m) => `${m[1]} have eaten`,
    reason: 'After "modal + have", use the past participle: "eaten", not "ate".',
  }),
  createRegexRule({
    id: 'VT_MOD_drove',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+drove\b/i,
    suggestion: (m) => `${m[1]} have driven`,
    reason: 'After "modal + have", use the past participle: "driven", not "drove".',
  }),
  createRegexRule({
    id: 'VT_MOD_spoke',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+spoke\b/i,
    suggestion: (m) => `${m[1]} have spoken`,
    reason: 'After "modal + have", use the past participle: "spoken", not "spoke".',
  }),
  createRegexRule({
    id: 'VT_MOD_wrote',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+wrote\b/i,
    suggestion: (m) => `${m[1]} have written`,
    reason: 'After "modal + have", use the past participle: "written", not "wrote".',
  }),
  createRegexRule({
    id: 'VT_MOD_broke',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+broke\b/i,
    suggestion: (m) => `${m[1]} have broken`,
    reason: 'After "modal + have", use the past participle: "broken", not "broke".',
  }),
  createRegexRule({
    id: 'VT_MOD_took',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+took\b/i,
    suggestion: (m) => `${m[1]} have taken`,
    reason: 'After "modal + have", use the past participle: "taken", not "took".',
  }),
  createRegexRule({
    id: 'VT_MOD_saw',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+saw\b/i,
    suggestion: (m) => `${m[1]} have seen`,
    reason: 'After "modal + have", use the past participle: "seen", not "saw".',
  }),
  createRegexRule({
    id: 'VT_MOD_gave',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+gave\b/i,
    suggestion: (m) => `${m[1]} have given`,
    reason: 'After "modal + have", use the past participle: "given", not "gave".',
  }),
  createRegexRule({
    id: 'VT_MOD_came',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+came\b/i,
    suggestion: (m) => `${m[1]} have come`,
    reason: 'After "modal + have", use the past participle: "come", not "came".',
  }),
  createRegexRule({
    id: 'VT_MOD_did',
    category: 'grammar',
    pattern: /\b(should|could|would|might|must|may)\s+have\s+did\b/i,
    suggestion: (m) => `${m[1]} have done`,
    reason: 'After "modal + have", use the past participle: "done", not "did".',
  }),

  // ═══ Have + wrong participle (VT_IRR_002) ═══
  createRegexRule({
    id: 'VT_have_went',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+went\b/i,
    suggestion: (m) => `${m[1]} gone`,
    reason: 'Use past participle "gone" after have/has/had, not "went".',
  }),
  createRegexRule({
    id: 'VT_have_ate',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+ate\b/i,
    suggestion: (m) => `${m[1]} eaten`,
    reason: 'Use past participle "eaten" after have/has/had, not "ate".',
  }),
  createRegexRule({
    id: 'VT_have_drove',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+drove\b/i,
    suggestion: (m) => `${m[1]} driven`,
    reason: 'Use past participle "driven" after have/has/had.',
  }),
  createRegexRule({
    id: 'VT_have_spoke',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+spoke\b/i,
    suggestion: (m) => `${m[1]} spoken`,
    reason: 'Use past participle "spoken" after have/has/had.',
  }),
  createRegexRule({
    id: 'VT_have_wrote',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+wrote\b/i,
    suggestion: (m) => `${m[1]} written`,
    reason: 'Use past participle "written" after have/has/had.',
  }),
  createRegexRule({
    id: 'VT_have_broke',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+broke\b/i,
    suggestion: (m) => `${m[1]} broken`,
    reason: 'Use past participle "broken" after have/has/had.',
  }),
  createRegexRule({
    id: 'VT_have_took',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+took\b/i,
    suggestion: (m) => `${m[1]} taken`,
    reason: 'Use past participle "taken" after have/has/had.',
  }),
  createRegexRule({
    id: 'VT_have_saw',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+saw\b/i,
    suggestion: (m) => `${m[1]} seen`,
    reason: 'Use past participle "seen" after have/has/had.',
  }),
  createRegexRule({
    id: 'VT_have_ran',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+ran\b/i,
    suggestion: (m) => `${m[1]} run`,
    reason: 'Use past participle "run" after have/has/had.',
  }),
  createRegexRule({
    id: 'VT_have_gave',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+gave\b/i,
    suggestion: (m) => `${m[1]} given`,
    reason: 'Use past participle "given" after have/has/had.',
  }),
  createRegexRule({
    id: 'VT_have_did',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+did\b/i,
    suggestion: (m) => `${m[1]} done`,
    reason: 'Use past participle "done" after have/has/had.',
  }),
  createRegexRule({
    id: 'VT_have_swam',
    category: 'grammar',
    pattern: /\b(have|has|had)\s+swam\b/i,
    suggestion: (m) => `${m[1]} swum`,
    reason: 'Use past participle "swum" after have/has/had.',
  }),

  // ═══ Subjunctive Mood (VT_SBJ) ═══
  createRegexRule({
    id: 'VT_SBJ_was',
    category: 'grammar',
    pattern: /\b(if|as\s+if|as\s+though|wish|wished)\s+(I|he|she|it)\s+was\b/i,
    suggestion: (m) => `${m[1]} ${m[2]} were`,
    reason: 'In hypothetical conditions, use "were" for all subjects (subjunctive mood).',
  }),
  createRegexRule({
    id: 'VT_SBJ_recommend',
    category: 'grammar',
    pattern:
      /\b(recommend|suggest|demand|insist|request|require|propose|urge)\s+that\s+(he|she|it)\s+(goes|has|is|was|does|takes|makes|gives|comes|leaves|stays|starts|stops|works|plays|reads|writes|runs|eats|drinks|sleeps)\b/i,
    suggestion: (m) =>
      `${m[1]} that ${m[2]} ${(m[3] || '').replace(/s$/, '').replace(/es$/, '').replace('goes', 'go').replace('has', 'have').replace('is', 'be').replace('was', 'be').replace('does', 'do')}`,
    reason:
      'Use the base form of the verb (no -s) in subjunctive constructions after verbs of demand or recommendation.',
  }),

  // ═══ Stative Verbs in Progressive (VT_STV) ═══
  createRegexRule({
    id: 'VT_STV_know',
    category: 'grammar',
    pattern: /\b(am|is|are|was|were)\s+knowing\b/i,
    suggestion: (m) =>
      `${({ am: '', is: '', are: '', was: '', were: '' } as Record<string, string>)[m[1]?.toLowerCase() || ''] !== undefined ? (m[1]?.toLowerCase() === 'am' ? 'know' : m[1]?.toLowerCase() === 'is' ? 'knows' : 'know') : 'know'}`,
    reason: '"Know" is a stative verb and should not be used in progressive form.',
  }),
  createRegexRule({
    id: 'VT_STV_believe',
    category: 'grammar',
    pattern: /\b(am|is|are|was|were)\s+believing\b/i,
    suggestion: 'believe',
    reason: '"Believe" is a stative verb. Use simple tense instead.',
  }),
  createRegexRule({
    id: 'VT_STV_own',
    category: 'grammar',
    pattern: /\b(am|is|are|was|were)\s+owning\b/i,
    suggestion: 'own',
    reason: '"Own" is a stative verb. Use "own" instead of "is owning".',
  }),
  createRegexRule({
    id: 'VT_STV_belong',
    category: 'grammar',
    pattern: /\b(am|is|are|was|were)\s+belonging\b/i,
    suggestion: 'belong',
    reason: '"Belong" is a stative verb. Use simple tense.',
  }),
  createRegexRule({
    id: 'VT_STV_consist',
    category: 'grammar',
    pattern: /\b(am|is|are|was|were)\s+consisting\b/i,
    suggestion: 'consist',
    reason: '"Consist" is a stative verb. Use simple tense.',
  }),
  createRegexRule({
    id: 'VT_STV_contain',
    category: 'grammar',
    pattern: /\b(am|is|are|was|were)\s+containing\b/i,
    suggestion: 'contain',
    reason: '"Contain" is a stative verb. Use simple tense.',
  }),
  createRegexRule({
    id: 'VT_STV_depend',
    category: 'grammar',
    pattern: /\b(am|is|are|was|were)\s+depending\b/i,
    suggestion: 'depend',
    reason: '"Depend" is a stative verb. Use "depends on" instead.',
  }),
  createRegexRule({
    id: 'VT_STV_prefer',
    category: 'grammar',
    pattern: /\b(am|is|are|was|were)\s+preferring\b/i,
    suggestion: 'prefer',
    reason: '"Prefer" is a stative verb. Use simple tense.',
  }),
  createRegexRule({
    id: 'VT_STV_seem',
    category: 'grammar',
    pattern: /\b(am|is|are|was|were)\s+seeming\b/i,
    suggestion: 'seem',
    reason: '"Seem" is a stative verb. Use simple tense.',
  }),
  createRegexRule({
    id: 'VT_STV_appear',
    category: 'grammar',
    pattern: /\b(am|is|are|was|were)\s+appearing\b/i,
    suggestion: 'appear',
    reason: '"Appear" is a stative verb (when meaning "seem"). Use simple tense.',
  }),

  // ═══ Verb + Wrong Preposition Collocations (VT_COL) ═══
  createRegexRule({
    id: 'VT_COL_discuss_about',
    category: 'grammar',
    pattern: /\bdiscuss\s+about\b/i,
    suggestion: 'discuss',
    reason: '"Discuss" is transitive — no "about" needed.',
  }),
  createRegexRule({
    id: 'VT_COL_reach_to',
    category: 'grammar',
    pattern: /\breached?\s+to\s+(the|a|his|her|their|our|my|your|its)\b/i,
    suggestion: (m) => `reached ${m[1]}`,
    reason: '"Reach" is transitive — no "to" needed.',
  }),
  createRegexRule({
    id: 'VT_COL_enter_into',
    category: 'grammar',
    pattern:
      /\bentered?\s+into\s+(the|a|his|her|their|our|my|your|its)\s+(room|house|building|office|store|shop|hall|class|school|hospital|church|kitchen|bedroom|bathroom|garage|garden|park|stadium|theater|theatre|museum|library|restaurant|cafe|bar|club|gym|pool|elevator|lift)b/i,
    suggestion: (m) => `entered ${m[1]} ${m[2]}`,
    reason: '"Enter" is transitive for physical spaces — no "into" needed.',
  }),
  createRegexRule({
    id: 'VT_COL_cope_up',
    category: 'grammar',
    pattern: /\bcope\s+up\s+with\b/i,
    suggestion: 'cope with',
    reason: 'The correct phrase is "cope with", not "cope up with".',
  }),
  createRegexRule({
    id: 'VT_COL_comprise_of',
    category: 'grammar',
    pattern: /\bcomprises?\s+of\b/i,
    suggestion: 'comprises',
    reason: '"Comprises" means "is made up of" — don\'t add "of". Or use "is composed of".',
  }),
  createRegexRule({
    id: 'VT_COL_emphasize_on',
    category: 'grammar',
    pattern: /\bemphasizes?\s+on\b/i,
    suggestion: 'emphasize',
    reason: '"Emphasize" is transitive — no "on" needed.',
  }),
  createRegexRule({
    id: 'VT_COL_mention_about',
    category: 'grammar',
    pattern: /\bmentioned?\s+about\b/i,
    suggestion: 'mentioned',
    reason: '"Mention" is transitive — no "about" needed.',
  }),
];
